apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: |-
    - op: add
      path: /metadata/annotations/eks.amazonaws.com~1role-arn
      value: ${ecriamrolearn}
  target:
    kind: ServiceAccount
    name: ecr-credentials-sync
- patch: |-
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/0/env
      value:
      - name: APP_MODE
        value: irsa
      - name: APP_AWS_REGION
        value: ${ecrregion}
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/1/env/1/value
      value: "id-${ecraccountid}"
    - op: replace
      path: /spec/jobTemplate/spec/template/spec/containers/1/env/2/value
      value: "${ecrregion}"
  target:
    kind: CronJob
    name: ecr-credentials-sync
resources:
- ../base
